# Generated by Django 5.0 on 2026-04-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
