# Generated by Django 5.2.12 on 2026-06-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
