# Generated by Django 5.2.12 on 2026-06-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.CharField(blank=True, choices=[('hobbies', 'Hobbies'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('food', 'Food'), ('people', 'People'), ('sports', 'Sports'), ('miscellaneous', 'Miscellaneous')], max_length=50, null=True),
        ),
    ]
